Update issue templates
cesarbruschetta/load-system pull request #1
Opened 2019-04-24 14:34 UTC by rafaelmpessoa

add template for issues

2019-04-24 15:51 UTC, cesarbruschetta approved these changes

2019-04-27 15:12 UTC, julianeventeu approved these changes

2019-04-27 16:24 UTC, julianeventeu requested changes
Rafael, can you create a folder .github and move these files to this folder?
This way we can follow the pattern suggested by GitHub.
https://help.github.com/en/articles/setting-guidelines-for-repository-contributors

2019-04-28 23:21 UTC, julianeventeu approved these changes

2019-04-28 23:21 UTC, merged