APIs design fixes#2
cesarbruschetta/load-system pull request #3
Opened 2019-04-25 22:54 UTC by julianeventeu

Criado modelo das APIs usando a especificação OpenAPI (swagger), alem das respostas afirmativas, fiz o mapeamento de erros 500 para os endpoints que enviam path parameter, pois o servidor pode retornar erro informando que não encontrou o id do loan, por exemplo.

2019-04-26 03:22 UTC, dariodinizg commented
Eu coloquei o código no swagger e ele está entregando um errro, dizendo que o método GET não tem requestbody da linha 59.

2019-04-26 04:14 UTC, dariodinizg commented on loan_system.yaml
> +          description: The Loan ID
Pelo que entendi, o parametro para o GET deveria ser uma data, certo?

E entendi balance deveria ser trazido dentro da resposta 200, mas ele está sendo chamado no requestBody.

2019-04-29 22:19 UTC, AlexandreProenca requested changes

2019-04-29 22:19 UTC, AlexandreProenca commented on loan_system.raml
> +title: Loans API
I think that we can describe better the API like this
```suggestion
title: Fintech API
baseUri: https://squad5.hero
protocols: [ HTTP, HTTPS ]
mediaType:  application/json
description: API to manage the loan payments control system from a fintech 
version: 0.0.1
```

2019-04-29 22:19 UTC, AlexandreProenca commented on loan_system.raml
> +mediaType: application/json
We need describe securitySchemes like this
```suggestion
securitySchemes:
  JWT:
    description: Authentic this to any method that needs a valid JWT to be set.
    type: x-{other}
    describedBy:
      headers:
        Authorization:
            description: X-AuthToken
            type: string
            required: true
      responses:
        401:
          description: Authentication problem (JWT not set or expired)
    settings:
      roles: []
```

2019-04-29 22:19 UTC, AlexandreProenca commented on loan_system.raml
> +  Loan_info:
This is a calculated data, we never save calculated data, we need just return this information.

2019-04-29 22:19 UTC, AlexandreProenca commented on loan_system.raml
> +  Balance:
Calculated data

2019-04-29 22:19 UTC, AlexandreProenca commented on loan_system.raml
> +  LoanBalance:
Calculated data

2019-04-29 22:19 UTC, AlexandreProenca commented on loan_system.raml
> +  Payment:
Payment is not an object, this is arguments passed by body request

2019-04-29 22:19 UTC, AlexandreProenca commented on loan_system.raml
> +/loan:
```suggestion
/loans:
  post:
    description: Create a loan application. Loans are automatically accepted.
    securedBy: JWT
    body:
      application/json:
        type: Loan
        example: {"amount": 1000, "term": 12, "rate": 0.05, "date": "2019-05-09 03:18Z" }
    responses:
        201:
          body:
            application/json:
              example: {"id": 1, "installment": 85.60 }
        401:
          body: 
            application/json:
              example: {"message": "Forbiden"}
```

2019-05-04 01:06 UTC, cesarbruschetta approved these changes

2019-05-04 01:07 UTC, AlexandreProenca approved these changes

2019-05-04 01:07 UTC, merged